[build]
  base = "sb-haircare"
  command = "npm run build:web"
  publish = "sb-haircare/dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
